### ISSUE TITLE
MqttFuture这个类的作用是什么？

### ISSUE THREAD

**Issue by hallkk** [DavidDingXu/panda-mqtt#1]
```java
MqttFuture mqttFuture = new MqttFuture(mqttMessage, timeout);
        try {
            producer.send(msg);
        } catch (ONSClientException e) {
            mqttFuture.cancel();
        }
        return mqttFuture.get();
```

没有理解这里有什么作用，本身`producer.send(msg);`已经是个同步方法了

**Comment by DavidDingXu** [comment]
> ```java
> ```java
> MqttFuture mqttFuture = new MqttFuture(mqttMessage, timeout);
>         try {
>             producer.send(msg);
>         } catch (ONSClientException e) {
>             mqttFuture.cancel();
>         }
>         return mqttFuture.get();
> ```
> 
> 
> 没有理解这里有什么作用，本身producer.send(msg);已经是个同步方法了
> ```

producer.send(msg);本身只是将消息publish了，这边需要同步等待消费端消费消息后的响应结果。
这是一套请求和响应的同步机制来达到PUB/SUB异步通信的伪同步调用
